import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css'
import { createTheme, MantineProvider } from '@mantine/core'

const inter = Inter({ subsets: ['latin'] })

const theme = createTheme({
	/** Put your mantine theme override here */
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<MantineProvider theme={theme}>{children}</MantineProvider>
			</body>
		</html>
	)
}
